module.exports = {
  users: [
    {
      userID: 1,
      username: "user1",
      email: "user1@email.com",
      password: "password1",
      budgetIDs: [1, 3],
      transactionIDs: [1, 4, 8],
    },
    {
      userID: 2,
      username: "user2",
      email: "user2@email.com",
      password: "password2",
      budgetIDs: [1, 2],
      transactionIDs: [2, 6],
    },
    {
      userID: 3,
      username: "user3",
      email: "user3@email.com",
      password: "password3",
      budgetIDs: [2, 3],
      transactionIDs: [5, 9, 10],
    },
    {
      userID: 4,
      username: "user4",
      email: "user4@email.com",
      password: "password4",
      budgetIDs: [3],
      transactionIDs: [3, 7],
    },
  ],

  budgets: [
    {
      budgetID: 1,
      budgetName: "budget1",
      totalAmount: 215.23,
      startDate: "",
      endDate: "",
      userIDs: [1, 2],
      transactionIDs: [1, 6],
    },
    {
      budgetID: 2,
      budgetName: "budget2",
      totalAmount: -196.17,
      startDate: "",
      endDate: "",
      userIDs: [2, 3],
      transactionIDs: [2, 5, 9],
    },
    {
      budgetID: 3,
      budgetName: "budget3",
      totalAmount: 3.56,
      startDate: "",
      endDate: "",
      userIDs: [1, 3, 4],
      transactionIDs: [3, 4, 7, 8, 10],
    },
  ],

  transactions: [
    {
      transactionID: 1,
      userID: 1,
      budgetID: 1,
      categoryID: 0,
      title: "",
      description: "",
      amount: 152.61,
      date: "",
    },
    {
      transactionID: 2,
      userID: 2,
      budgetID: 2,
      categoryID: 0,
      title: "",
      description: "",
      amount: -120.52,
      date: "",
    },
    {
      transactionID: 3,
      userID: 4,
      budgetID: 3,
      categoryID: 0,
      title: "",
      description: "",
      amount: 20.82,
      date: "",
    },
    {
      transactionID: 4,
      userID: 1,
      budgetID: 3,
      categoryID: 0,
      title: "",
      description: "",
      amount: -30.99,
      date: "",
    },
    {
      transactionID: 5,
      userID: 3,
      budgetID: 2,
      categoryID: 0,
      title: "",
      description: "",
      amount: 15.18,
      date: "",
    },
    {
      transactionID: 6,
      userID: 2,
      budgetID: 1,
      categoryID: 0,
      title: "",
      description: "",
      amount: 62.62,
      date: "",
    },
    {
      transactionID: 7,
      userID: 4,
      budgetID: 3,
      categoryID: 0,
      title: "",
      description: "",
      amount: -32.17,
      date: "",
    },
    {
      transactionID: 8,
      userID: 1,
      budgetID: 3,
      categoryID: 0,
      title: "",
      description: "",
      amount: 70.2,
      date: "",
    },
    {
      transactionID: 9,
      userID: 3,
      budgetID: 2,
      categoryID: 0,
      title: "",
      description: "",
      amount: -90.82,
      date: "",
    },
    {
      transactionID: 10,
      userID: 3,
      budgetID: 3,
      categoryID: 0,
      title: "",
      description: "",
      amount: -24.3,
      date: "",
    },
  ],
};
